export type ADD_DRUG_API_DATA = "ADD_DRUG_API_DATA";
export type LOAD_DRUG_DATA = "LOAD_DRUG_DATA";

export const ADD_DRUG_API_DATA: ADD_DRUG_API_DATA = "ADD_DRUG_API_DATA";
export const LOAD_DRUG_DATA: LOAD_DRUG_DATA = "LOAD_DRUG_DATA";
